name: Infra-deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.tfstate"
      - "**.tfstate.encrypted"

env:
  # Secrets for cloudflare
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}

jobs:
  terraform:
    name: "Terraform Infrastructure"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the infra directory.
        working-directory: ./infra

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Download Encrypted Artifact & Decrypt Artifact
        uses: badgerhobbs/terraform-state@v2
        with:
          encryption_key: ${{ secrets.ENCRYPTION_KEY }}
          operation: download
          location: repository
          directory: infra
          github_token: ${{ secrets.gh_access_token }}
        continue-on-error: true

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.3

      - name: Terraform init
        id: init
        run: terraform init -upgrade

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        continue-on-error: true

      - name: Encrypt Artifact & Upload Encrypted Artifact
        uses: badgerhobbs/terraform-state@v2
        with:
          encryption_key: ${{ secrets.ENCRYPTION_KEY }}
          operation: upload
          location: repository
          directory: infra
          github_token: ${{ secrets.gh_access_token }}
